#!/bin/bash
#SBATCH -J TB_BxD_CAPE
#SBATCH -N 1 # number of nodes
#SBATCH -n 1 # number of cores
#SBATCH --mem=8G # memory pool for all cores
#SBATCH -t 0-24:00 # time (D-HH:MM)
#SBATCH -o slurm.%N.%j.out # STDOUT
#SBATCH -e slurm.%N.%j.err # STDERR
#SBATCH --mail-user=anna.tyler@jax.org
#SBATCH --mail-type=END

# example use: sbatch TB_BxD_CAPE

cd $SLURM_SUBMIT_DIR

module load singularity

singularity exec /projects/carter-lab/atyler/Containers/kinship_analysis_latest.sif R -e "rmarkdown::render(here::here('documents', 'BxD_CAPE.Rmd')"

